apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  type: LoadBalancer  # AWS 로드밸런서(CLB/NLB)를 자동으로 연결해줌
  selector:
    app: my-web-app   # deployment의 label과 똑같아야 함
  ports:
    - protocol: TCP
      port: 80        # 외부에서 접속할 포트
      targetPort: 8080  # 컨테이너 내부 포트